version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
    - "8000:80"
    volumes:
    - ./storage/logs:/var/www/html/storage/logs
    # depends_on:
    # - postgres
    # - redis
    env_file:
    - .env.docker
    networks:
    - snipeit-backend

  postgres:
    image: postgres
    volumes:
    - db:/var/lib/pgsql
    env_file:
    - .env.docker
    networks:
    - snipeit-backend
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:6.2.5-buster
  #   networks:
  #   - snipeit-backend

  # mailhog:
  #   image: mailhog/mailhog:v1.0.1
  #   ports:
  #   # - 1025:1025
  #   - "8025:8025"
  #   networks:
  #   - snipeit-backend


volumes:
  db: {}

networks:
  snipeit-backend: {}
